### ISSUE TITLE
Discussion: can the method differentiate the background classes?

### ISSUE THREAD

**Issue by KevinChen880723** [lukemelas/deep-spectral-segmentation#11]
Hi, thank you for providing this awsome work!

After reading the paper, I realized that we are highly relying on color, spatial, and the features extracted by the DINO algorithm.
So if we train a DINO model by the dataset that doesn't include background classes like road and sidewalk, and this two different classes shared the similar color and spatial features, can the eigen map still differentiate this two classes? 
Thanks again for the discussion!!

![image](https://user-images.githubusercontent.com/55487740/195539501-75c1ade5-3d94-4e95-a8dd-34c1789a6299.png)

Kevin

**Comment by lukemelas** [comment]
Thanks for the question and for starting this discussion. 

Yes, I agree that the model relies heavily on local features like texture and color. This is a property that has been observed in a bunch of other settings as well (for example, [Deep ViT Features as Dense Visual Descriptors](https://arxiv.org/abs/2112.05814) from Tali Dekel's group). 

As to whether it can differentiate the classes, it depends heavily on the individual setting. Sometimes it is surprisingly good at separating classes, and other times it groups different classes together.

Hope this helps! 
Luke

**Comment by KevinChen880723** [comment]
Thanks a lot for providing the good information and the discussion!

Kevin
