### ISSUE TITLE
typo in semantic segmentation example - "dino_vitb16" instead of "dino_vits16"

### ISSUE THREAD

**Issue by alexaatm** [lukemelas/deep-spectral-segmentation#16]
Hi!
I am trying to run semantic segmentation example, following the readme, and it was failing to find the directory. After debugging a bit, turned out an issue was in the MODEL variable in the very start of the example, where there was "dino_vitb16" instead of "dino_vits16" (b instead of s). 

Just in case anyone had the same small issue ;)

**Comment by lukemelas** [comment]
Thanks! Updated.
