### ISSUE TITLE
Twice conversion to float for `image_lr` 

### ISSUE THREAD

**Issue by fuersta** [lukemelas/deep-spectral-segmentation#17]
Hi,
in
https://github.com/lukemelas/deep-spectral-segmentation/blob/main/extract/extract.py#L204
and 
https://github.com/lukemelas/deep-spectral-segmentation/blob/main/extract/extract.py#L208
https://github.com/lukemelas/deep-spectral-segmentation/blob/main/extract/extract.py#L210
you convert `image_lr` to float by dividing through 255. 
Looks like a bug to me.

**Comment by lukemelas** [comment]
True, thanks for catching that! Fixed.

Luke
