### ISSUE TITLE
Object Localization Problem

### ISSUE THREAD

**Issue by SMSD75** [lukemelas/deep-spectral-segmentation#19]
Hi, 

Thank you for your beautiful research. I am facing an issue with the data loader when it comes to object localization. The address for the VOC12 dataset seems to be incorrect, and there is no guide available to set it up properly. The code expects VOC dataset to exist in the directory "datasets"; however, in the previous sections, we set it up in "data". Even, when I set up the address to "data" it cannot load it.  Would you please guide me on this? 

Thanks.

**Comment by SMSD75** [comment]
Solved

**Comment by sidgairo18** [comment]
Hi @SMSD75 ,
How did you solve this?
