### ISSUE TITLE
CRF up-sampled images are blank

### ISSUE THREAD

**Issue by SMSD75** [lukemelas/deep-spectral-segmentation#20]
Hi, 

I am exactly following the steps mentioned for object segmentation. I can see the segmentations in the folder "patch". However, when I up sample them using CRF, everything becomes a big black picture. Do you know what might be wrong?

**Comment by SMSD75** [comment]
Thank you for your reply. I figured out the reason for the mismatch. The saved images in the folder CRF are ok; the problem with black image was because of the scales of the number; However, I am getting a pretty low number for DINO-s16 on CUB. It is only 30% for MIOU. In fact, the reason that I thought the CRF images were not ok was the low score for DINO-s16.

**Comment by lukemelas** [comment]
Glad to hear the CRF is working correctly. 

Hmm, the score should definitely be higher. When you look at the images, do they look correct? For CUB it should almost always get the bird. Sometimes it also get the branch or misses out on some of the fine details.

**Comment by SMSD75** [comment]
As far as I see, the patches are ok, although, because the size of the images is very different from the DINO's spatial resolution, when resizing some of them, they become inaccurate. To me, this makes sense since in `_extract_crf_segmentations` the following code exists: 

`    # Sizes
    P = downsample_factor
    H, W = image.shape[:2]
    H_patch, W_patch = H // P, W // P
    H_pad, W_pad = H_patch * P, W_patch * P
 `   
 `
    # Resize and expand
    segmap_upscaled = cv2.resize(segmap, dsize=(W_pad, H_pad), interpolation=cv2.INTER_NEAREST)  # (H_pad, W_pad)
    segmap_orig_res = cv2.resize(segmap, dsize=(W, H), interpolation=cv2.INTER_NEAREST)  # (H, W)
    segmap_orig_res[:H_pad, :W_pad] = segmap_upscaled  # replace with the correctly upscaled version, just in case they are different
`
, which somehow merges the upscaled images from different approaches to be sure that everything is covered. This might increase accuracy but reduce MIOU. For instance, I get 80% ACC.

**Comment by SMSD75** [comment]
Thank you for your kind answering. I solved the issue. The file names in the images.txt and the directory in which the images existed were not aligned. After sorting the names, I reproduced the results.
