### ISSUE TITLE
Class name of evaluation results

### ISSUE THREAD

**Issue by YScheung** [lukemelas/deep-spectral-segmentation#22]
Hi, I have successfully obtained the semantic segmentation evaluation results on PASCAL VOC2012 by running eval.py. However, I would like to know what're the class names corresponding to the list of 'jaccards_all_categs' result ?

![Screenshot 2023-04-30 at 2 36 46 AM](https://user-images.githubusercontent.com/72407100/235318827-f1aed433-0263-42dc-8388-43eb24c7e7c6.png)

Many thanks !!

**Comment by chandagrover** [comment]
Hi, 
@YScheung: Could you please tell how you got 35.88 mIoU scores? I am getting 24.27 mIoU score.
![Screenshot from 2023-10-05 17-34-25](https://github.com/lukemelas/deep-spectral-segmentation/assets/31935472/502b3132-7a9e-47b6-adc0-fd0b87c899ea)
