### ISSUE TITLE
problem of dino on semantic-segmentation

### ISSUE THREAD

**Issue by liuxingbin** [lukemelas/deep-spectral-segmentation#6]
Hi!
It's a great job for unsupervised detection and segmentation. When I try to reproduce the dino-segmentation result in table-4, I only get 19.55 which is far lower than the value reported in your paper(30.8+-2.7). Did I miss something? Looking forward to your reply.

**Comment by lukemelas** [comment]
Hi, thanks for the question. I received the email you sent me and responded to you there before seeing this issue. I'm closing this as a result -- if we find anything notable I'll post it here.

**Comment by hq-deng** [comment]
Hello, do you reproduce the result successfully? I also cannot achieve the good results.

**Comment by liuxingbin** [comment]
> Hello, do you reproduce the result successfully? I also cannot achieve the good results.

sadly no.
