### ISSUE TITLE
Eigenvector effect

### ISSUE THREAD

**Issue by xiaoerqi** [lukemelas/deep-spectral-segmentation#8]
Great work, thank you!

After I use the code, the result of the eigenvector is much worse than that of the API in the hugging face. May I ask whether the model used in the hugging face has a fine tune on other data sets? I'm not too sure about the difference between the PAI provided in the project and that in the hugging face

**Comment by lukemelas** [comment]
Hi xiaoerqi, thanks for the issue. The code on HF should be exactly the same as the code here. You can see the code on the "Files and versions" tab on HF. What do you mean when you say they look different?

**Comment by xiaoerqi** [comment]
Thank you very much, I read the code in HF, the model used is Vitbase, and I used the default vitsmall before, so the effect is relatively poor, now I can get the same result, thanks again for the answer

**Comment by lukemelas** [comment]
Glad to hear it. Closing the issue -- if something else comes up, feel free to open it again.
